baseURL: https://raian0406.github.io
languageCode: en-us
title: Home
theme: PaperMod
env: production
copyright: Raian LEFGOUM 2022,
enableEmoji: true
outputs:
  home:
    - JSON
    - RSS
    - HTML
defaultContentLanguage: en
languages:
  en:
    languageName: ":us:"
    profileMode:
      enabled: true
      title: "Raian LEFGOUM"
      subtitle: "PhD Student in Applied Mathematics / Stochastic Optimization"
      imageURL: /photo.jpg
      imageWidth: 312
      imageHeight: 335


params:
  displayFullLangName: true
  name: Home
  disableSpecial1stPost: true
  ShowReadingTime: false
  ShowToc: false
  TocOpen: false
  ShowBreadCrumbs: false
  ShowPostNavLinks: true
  comments: true
  socialIcons:
    - name: LinkedIn
      url: https://fr.linkedin.com/in/raian-lefgoum-680312162

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true
